# Generated by Django 5.1.2 on 2024-10-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CrudBlog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tag",
            field=models.CharField(default="default tag", max_length=255),
        ),
    ]
