# Generated by Django 5.1.2 on 2024-10-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CrudBlog", "0002_post_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tag",
            field=models.CharField(max_length=255),
        ),
    ]
