# Generated by Django 5.1.2 on 2024-10-31 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CrudBlog", "0005_alter_post_post_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
