# Generated by Django 5.1.2 on 2024-11-05 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CrudBlog", "0013_alter_profile_bio_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="date_addede",
            new_name="date_added",
        ),
    ]
