# Generated by Django 5.1.2 on 2024-11-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CrudBlog", "0014_rename_date_addede_comment_date_added"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="category",
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ManyToManyField(related_name="posts", to="CrudBlog.category"),
        ),
    ]
